// Code generated by "stringer -type=Type"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[FEATURE-2]
	_ = x[BACKGROUND-3]
	_ = x[SCENARIO-4]
	_ = x[GIVEN-5]
	_ = x[WHEN-6]
	_ = x[THEN-7]
	_ = x[AND-8]
	_ = x[BUT-9]
	_ = x[EXAMPLES-10]
	_ = x[COMMENT-11]
	_ = x[TEXT-12]
}

const _Type_name = "ILLEGALEOFFEATUREBACKGROUNDSCENARIOGIVENWHENTHENANDBUTEXAMPLESCOMMENTTEXT"

var _Type_index = [...]uint8{0, 7, 10, 17, 27, 35, 40, 44, 48, 51, 54, 62, 69, 73}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
